include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.chopper.dart'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    - 'lib/**.g.dart'
    - build/**

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    prefer_const_constructors: false
    avoid_print: true
    no_leading_underscores_for_local_identifiers: false
